export type UniverseStock = { symbol: string; name: string };

export const DJIA: UniverseStock[] = [
  { symbol: "AAPL", name: "Apple" },
  { symbol: "AMGN", name: "Amgen" },
  { symbol: "AMZN", name: "Amazon" },
  { symbol: "AXP", name: "American Express" },
  { symbol: "BA", name: "Boeing" },
  { symbol: "CAT", name: "Caterpillar" },
  { symbol: "CRM", name: "Salesforce" },
  { symbol: "CSCO", name: "Cisco" },
  { symbol: "CVX", name: "Chevron" },
  { symbol: "DIS", name: "Disney" },
  { symbol: "DOW", name: "Dow" },
  { symbol: "GS", name: "Goldman Sachs" },
  { symbol: "HD", name: "Home Depot" },
  { symbol: "HON", name: "Honeywell" },
  { symbol: "IBM", name: "IBM" },
  { symbol: "INTC", name: "Intel" },
  { symbol: "JNJ", name: "Johnson & Johnson" },
  { symbol: "JPM", name: "JPMorgan Chase" },
  { symbol: "KO", name: "Coca-Cola" },
  { symbol: "MCD", name: "McDonald's" },
  { symbol: "MMM", name: "3M" },
  { symbol: "MRK", name: "Merck" },
  { symbol: "MSFT", name: "Microsoft" },
  { symbol: "NKE", name: "Nike" },
  { symbol: "PG", name: "Procter & Gamble" },
  { symbol: "TRV", name: "Travelers" },
  { symbol: "UNH", name: "UnitedHealth" },
  { symbol: "V", name: "Visa" },
  { symbol: "VZ", name: "Verizon" },
  { symbol: "WMT", name: "Walmart" },
];
